{% set version = "0.4.8" %}

package:
  name: pyct
  version: {{ version }}

build:
  number: 0
  noarch: python
  entry_points:
    - pyct=pyct.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyct-core {{ version }}
    - pyyaml
    - requests

test:
  imports:
    - pyct
    - pyct.cmd
  requires:
    - flake8
    - pytest
  commands:
    - pytest -v --pyargs pyct
    - pyct --help
    - pyct --version
    - pyct report --help
    - pyct report pyct python

about:
  home: http://github.com/pyviz-dev/pyct
  license: BSD-3-Clause
  license_family: BSD
  # in pyct-core
  # license_file: LICENSE.txt
  summary: 'Python package common tasks for users (e.g. copy examples, fetch data, ...)'
  doc_url: https://github.com/pyviz-dev/pyct
  dev_url: https://github.com/pyviz-dev/pyct

extra:
  recipe-maintainers:
    - ocefpaf
    - jbednar
